# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5805ecd7e72001319041dc09030305e526fc4442e7727295b97b365fa3885b3dda957fe6e80246c885c8dbfb3b003fcb51b43bdf1b21414f059d010a98d9da30

test:
  secret_key_base: 0be24c8b30f2f40e63d4253b059e2dfaf4e7e2df9469689f4a880d514b5385db6c6bff194dd0291c263321ed939593bc5d453ce6710b7e9930db89ab044551b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
